"""Shared operation requests (§FS-distribution.3.3.5, §FS-distribution.3.0.3)."""

# Each tuple is (fixture, operation, positional operands, keyword options).
# Use existing fixtures as authoritative inputs, without editing their goldens.
READ_CASES = (
    ("json-report", "check", (), {}),
    ("clean", "check", (), {}),
    ("check-empty-json", "check", (), {}),
    ("check-invalid-config-json", "check", (), {}),
    ("check-empty-scan-warning", "check", (), {}),
    ("workspace-include-root-false-unread-json", "check", (), {}),
    ("workspace-nested-include-root-false-list-project", "list_ids", (), {"projects": ("root",)}),
    ("check-rules-chapter-absent-suggestion", "check", (), {"suggestions": False}),
    ("check-rules-chapter-absent-suggestion", "check", (), {"suggestions": True}),
    ("check-only-rule-code-keeps-invalid-rule-json", "check", (),
     {"only": ("chapter-cardinality",)}),
    ("workspace-check-json-broken", "check", (), {}),
    ("json-report", "check", (), {"only": ("dangling",), "ignore": ("dangling",)}),
    ("json-report", "check", (), {"require_grounding": True, "full": True}),
    ("json-report", "check", (), {"rule": "Each FS must have exactly one Terms chapter.", "only_rule": True}),
    ("json-report", "scan", (), {}),
    ("check-invalid-config-json", "scan", (), {}),
    ("json-report", "show", ("FS-001-alpha",), {}),
    ("json-report", "show", ("FS-999-missing",), {}),
    ("show-ambiguous-id-json", "show", ("FS-001-login",), {}),
    ("show-ambiguous-section-json", "show", ("FS-001-login",), {"section": "1"}),
    ("json-report", "show_batch", (("FS-001-alpha", "FS-999-missing"),), {}),
    ("check-invalid-config-json", "show_batch", ((),), {}),
    ("check-invalid-config-json", "show_batch", (("FS-001-alpha",),), {}),
    ("json-report", "show_batch", (), {}),
    ("json-report", "refs", ("FS-001-alpha",), {}),
    ("json-report", "refs", ("FS-999-missing",), {}),
    ("show-ambiguous-id-json", "refs", ("FS-001-login",), {}),
    ("refs-ambiguous-shorthand-json", "refs", ("FS-042",), {}),
    ("workspace-refs-ambiguous-section-json", "refs", ("api/FS-001-alpha",),
     {"section": "1", "descendants": True}),
    ("json-report", "list_ids", (), {}),
    ("json-report", "list_ids", (), {"kinds": ("FS",), "unused": True}),
    ("json-report", "list_ids", (), {"selector": "FS-001-alpha"}),
    ("check-invalid-config-json", "list_ids", (), {}),
    ("workspace-list-unknown-project", "list_ids", (), {"projects": ("missing",)}),
    ("json-report", "list_sizes", (), {}),
    ("json-report", "list_sizes", (), {"units": ("words",), "top": 1}),
    ("check-invalid-config-json", "list_sizes", (), {}),
    ("json-report", "cover", (), {}),
    ("json-report", "cover", (), {"text": True}),
    ("check-invalid-config-json", "cover", (), {}),
    ("cover-lines-directory", "cover", (), {"lines": ("1",)}),
    ("json-report", "propose_id", ("FS", "Python façade"), {}),
    ("json-report", "propose_id", ("UNKNOWN", "Title"), {}),
    ("json-report", "propose_id", ("FS", ""), {}),
    ("check-invalid-config-json", "propose_id", ("FS", "Title"), {}),
    ("json-report", "effective_config", (), {}),
    ("check-invalid-config-json", "effective_config", (), {}),
    ("json-report", "validate_config", (), {}),
    ("check-invalid-config-json", "validate_config", (), {}),
    ("json-report", "complete_ids", ("FS-",), {"sections": True}),
    ("workspace-complete-ids", "complete_ids", (), {}),
    ("check-invalid-config-json", "complete_ids", (), {}),
    ("json-report", "reference_style", (), {}),
    ("check-invalid-config-json", "reference_style", (), {}),
    ("json-report", "integrations", (), {}),
    ("json-report", "agent_setup_instructions", (), {}),
)

# Reads whose root is one file of the fixture rather than the fixture itself
# (§FS-cover.6.1): (fixture, path under it, operation, positional operands,
# keyword options).
FILE_READ_CASES = (
    ("cover-lines-json", "docs/functional-spec/FS-001-alpha.md", "cover", (),
     {"lines": ("17", "1-14", "20-31", "33-49")}),
    ("cover-lines-source-json", "src/lib.rs", "cover", (), {"lines": ("1-10", "8")}),
    ("cover-lines-past-eof", "docs/functional-spec/FS-001-alpha.md", "cover", (),
     {"lines": ("45-50",)}),
    ("cover-lines-outside-scan", "notes.txt", "cover", (), {"lines": ("1",)}),
)

MUTATIONS = (
    ("fmt-shorthand-write", "fmt", (), {"write": False}),
    ("fmt-shorthand-write", "fmt", (), {"write": True}),
    ("fmt-shorthand-write", "fmt", (), {"write": True, "marker": True}),
    ("fmt-cross-refs-idempotent", "fmt", (), {"write": True, "cross_refs": False}),
    ("fmt-cross-refs-config-disabled", "fmt", (), {"write": True, "cross_refs": True}),
    ("fmt-embedded-value-refusal-stable", "fmt", (), {"write": True}),
    ("init-dry-run-default", "init", (), {"write": False, "no_vcs": True}),
    ("init-dry-run-default", "init", (), {"write": True, "no_vcs": True}),
    ("init-dry-run-default", "init", (), {"write": True, "check": True, "no_vcs": True}),
    ("init-invalid-config-is-an-error", "init", (), {"write": True}),
    ("init-force-overwrites", "init", (), {"write": True, "force": True}),
    ("json-report", "init", (), {"write": True, "force": True}),
    ("fetch-workspace-folder", "fetch", ("alpha/TICKET-1234",), {"write": True}),
    ("fetch-folder-refusal", "fetch", ("TICKET-1234",), {"write": True}),
    ("json-report", "integrations", ("kitty",), {"write": False}),
    ("json-report", "integrations", ("kitty",), {"write": True}),
    ("json-report", "integrations", ("iterm2",), {"write": True}),
    ("json-report", "integrations", (),
     {"write": True, "conversation": "link", "conversation_target": "vscode", "agent": "codex"}),
)
